# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'iOSAnimationDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSAnimationDemo
  pod 'SnapKit', '~> 0.21.1'

end
